"""add_knowledge_base_tables

Revision ID: 957415b5942f
Revises: cf8bd378af9c
Create Date: 2026-04-02 08:20:30.763597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957415b5942f'
down_revision: Union[str, Sequence[str], None] = 'cf8bd378af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='creating', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_datasets_org_id'), 'knowledge_base_datasets', ['org_id'], unique=False)
    op.create_table('knowledge_base_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('file_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('validation_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_uploads_org_id'), 'knowledge_base_uploads', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_uploads_org_id'), table_name='knowledge_base_uploads')
    op.drop_table('knowledge_base_uploads')
    op.drop_index(op.f('ix_knowledge_base_datasets_org_id'), table_name='knowledge_base_datasets')
    op.drop_table('knowledge_base_datasets')
    # ### end Alembic commands ###
